# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed2c6e67ab93f88f4077b1f58f98d2c21009fee812862eedc303aa7554fd52a5f52894de379114dfb12ba9dc6106cac0aff99e69bc16bbcaf4261236e8f88901

test:
  secret_key_base: 4ec082560626c4d98d36b0f33fb46d099a6c77f44fd5762e4633cd86a7bcb59df547e8e64dbb8ad60cfd82d609e3410b660bfeff1db6f38060ad79e731ffb41f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
